// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Data;

#pragma warning disable 1573, 1591
#nullable enable

namespace eshopBackend.DAL.DbSettings;

	public partial class EshopBackendDb : DataConnection
	{
		public EshopBackendDb()
		{
			InitDataContext();
		}

		public EshopBackendDb(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		public EshopBackendDb(DataOptions<EshopBackendDb> options)
			: base(options.Options)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}
