on:
  release:
    types: [created]
name: Release Binaries
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Publish for Windows
        run: dotnet publish -c Release -r win10-x64
      - name: Publish for Linux
        run: dotnet publish -c Release -r ubuntu.16.10-x64
      - name: Compress Windows binary
        run: tar -C eshopBackend.API/bin/Release/net7.0/win10-x64/publish/ -czvf Windows10-x64.tar.gz ./
      - name: Compress Linux binary
        run: tar -C eshopBackend.API/bin/Release/net7.0/ubuntu.16.10-x64/publish/ -czvf ubuntu.16.10-x64.tar.gz ./
      - name: Upload the Windows binary
        uses: diamondburned/action-upload-release@main
        with:
          files: Windows10-x64.tar.gz
      - name: Upload the Linux binary
        uses: diamondburned/action-upload-release@main
        with:
          files: ubuntu.16.10-x64.tar.gz
