on:
  release:
    types: [created]
name: Release Binaries
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Publish for Windows
        run: dotnet publish -c Release -r win10-x64
      - name: Publish for Linux
        run: dotnet publish -c Release -r ubuntu.16.10-x64
      - name: Upload the Windows artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Windows10-x64
          path: eshopBackend.API/bin/Release/net7.0/win10-x64/publish/
      - name: Upload the Linux artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu.16.10-x64
          path: eshopBackend.API/bin/Release/net7.0/ubuntu.16.10-x64/publish/
      - name: Release artifacts
        uses: SierraSoftworks/gh-releases@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}